Uniswap/uniswapx-parameterization-api

lib/quoters/WebhookQuoter.ts

Previously successful rfq responses were actually silent so hard to
debug any responses that were still considered successful

feat: add response to successful rfq log

---

bin/stacks/analytics-stack.ts
bin/stacks/api-stack.ts
bin/stacks/cron-stack.ts
bin/stacks/param-dashboard-stack.ts
lib/cron/fade-rate.ts
package.json
yarn.lock

Adds a cron job that runs every 5 minutes to query the Redshift cluster to calculate fade rate by fillers. Fade rate is defined as `(# unfilled orders + # filled orders with different actual filler address) / (# quote provided)`
Right now the cron lambda just prints out the result. A follow-up PR will store the result into a dynamo table (potentially) and putting fillers with high fade rate (exact number tbd) in the box.
**tests done**
Deployed locally to make sure the permissions are set up correctly;
Manually ran the queries in the prod param-api account, and got

feat: calculate filler fade rate using redshift data

---

bin/stacks/analytics-stack.ts
bin/stacks/cron-stack.ts

log filler in postedOrders table so that we can use user signed and submitted orders w/ exclusive fillers to as denominator to calculate fade rate

chore: add filler to postedOrders table

---

bin/app.ts
lib/cron/fade-rate.ts

fix the fade rate calculation query:
- exclude testnet orders
- expecting `fillTimestamp >= extract(epoch from (GETDATE() - INTERVAL '24 HOURS'));` means that we only considered **filled orders** because expired ones don't have `fillTimestamp`
also, force-execute the dynamo command

fix: fix sql query and execute dynamo command

---

bin/stacks/cron-stack.ts
lib/cron/fade-rate.ts

Change the Redshift query to do the following instead:
- get the last 20 quotes from the last 7 days for each filler address
- count total and unfilled orders (`actualFiller` != original filler address in quote)
- filter out those who provided less than 10 quotes
Also, move fade rate calculation to quote handler (future PR) since a filler entity can have multiple addresses

feat: change how we count faded quotes

---

bin/stacks/cron-stack.ts
lib/constants.ts
lib/cron/synth-switch.ts
lib/handlers/quote/injector.ts

add cron job to query redshift to determine if synthetic quotes should be turned on or off for pre-specific token pairs and trade sizes.

feat: add synth switch cron

---

bin/stacks/api-stack.ts

threshold is already 0.95 for SEV3, now we added eth out and it's likely to go above that for a while until quoters come on

fix: raise thresholds for GPA 4xx alarms even more

---

bin/stacks/cron-stack.ts
jest-dynamodb-config.js
lib/constants.ts
lib/cron/fade-rate.ts
lib/repositories/switch-repository.ts

having to rename the dynamo tables because we want to remove a sort key which isn't possible

fix: rename dynamo tables

---

bin/app.ts
bin/stacks/api-stack.ts

btw disabling provisioned concurrency for mockQuote endpoint
Bumping provisioned concurrency since we saw that provisionedConcurrencyRolloverRate (cold start rate) is ~90% for this service
Seems like max concurrent executions is ~200, so if we do 100 we can scale to max 5 * 100 = 500 which should more than cover it. Right now we're giving equal provisionedConcurrency to the /enabled and /quote endpoints which I think makes sense, they are both hit once per request.

fix: bump prov concurrency for endpoints from 5 to 100

---

bin/stacks/cron-dashboard-stack.ts
lib/cron/synth-switch.ts

We aren't disabling synth orders with negative outcomes because we don't have enough data points to meet the threshold.

chore: tune synth-switch 

---

lib/constants.ts
lib/cron/fade-rate.ts
lib/cron/synth-switch.ts
lib/handlers/quote/injector.ts

In order to support our beta test env we need to change the s3 bucket we read from based on the stage we are deployed in.

chore: add support for beta s3 config

---

bin/stacks/analytics-stack.ts
lib/cron/redshift-reaper.ts
lib/repositories/analytics-repository.ts

- Reduce Redshift retention to 1 month 
- delete (almost) all rows marked for deletion

chore: cron tweaks

---

lib/cron/redshift-reaper.ts
lib/repositories/base.ts

daily volume steadily increasing as we ramp up to 100%

chore: lower redshift reaper threshold to two weeks

---

lib/entities/QuoteResponse.ts
lib/handlers/quote/schema.ts

We require fillers to echo back quoteId and we should use that as the source of truth
right now, a bug exists such that a new quoteId is generated after we get back the response

fix: new quote id get generated after quote response

---

lib/handlers/blueprints/cw-log-firehose-processor.js

Currently the UniswapX analytics events are processed and stored in an intermediate S3 bucket as blobs of JSON objects without being newline-delimited or comma-separated. This works fine for ingestion to Redshift, but additional downstream transformations are required to transform them to newline-delimited JSON (JSONL) for ingestion to BigQuery. This PR changes the output of the S3 data to JSONL as part of the firehose processor's output, which has no impact on how the data is ingested into Redshift, but allows for simplification on the BigQuery ingestion.
**Testing**
I tested this change end-to-end in AWS by logging 4x RFQ requests in rapid succession, which produced a JSONL blob in S3 containing 4 JSON objects each on a new line. I checked for the same 4 `requestId`s in Redshift and …

chore: output intermediary S3 data as JSONL

---

lib/entities/analytics-events.ts
lib/quoters/WebhookQuoter.ts
test/providers/analytics/firehose.test.ts
test/providers/quoters/WebhookQuoter.test.ts

- adds `eventId` to AnalyticsEvent class for downstream deduping purposes
- updates AnalyticsEvent class to require `eventTime` class variable
- updates code to construct `AnalyticsEvent` before passing to sendAnalyticsEvent()

[chore] add eventId to AnalyticsEvent class

---

lib/entities/analytics-events.ts
lib/quoters/WebhookQuoter.ts
lib/util/time.ts
test/providers/quoters/WebhookQuoter.test.ts

- Updates AnalyticsEvent `eventTime` class variable to be an ISO string to ingest in BigQuery natively as a Timestamp type
- Updates `requestTime` and `responseTime` event properies logged with the QuoterWebhookResponse events.

[chore] AnalyticsEvent eventTime to ISO string

---

bin/stacks/analytics-stack.ts
bin/stacks/api-stack.ts

1. https://github.com/Uniswap/uniswapx-parameterization-api/pull/236 added a FirehoseLogger to the container injector, which is constructed using a `ANALYTICS_STREAM_ARN` environment variable as an argument
2. https://github.com/Uniswap/uniswapx-parameterization-api/pull/236 added `ANALYTICS_STREAM_ARN` environment variable to the lambda handlers initialized in `bin/stacks/api-stack.ts`, but did not add the environment variable to the Firehose lambda processors in `bin/stacks/analytics-stack.ts`
3. The logging to CloudWatch remained the same, but the Firehose lambda processors started to fail because the `ANALYTICS_STREAM_ARN` environment variable was missing and FirehoseLogger was constructed with an undefined `streamArn` param, so the logged events were not processed by firehose …

[fix] add analyticsStreamArn to processor lambdas env vars

---

jest.config.js
package.json
yarn.lock

Saw the backend team started using speedy web compiler and tested it out for UPA. Works well!
ts-jest has a 6 - 12 second lag when compiling. This compilation lag gets extra bad if you run jest in watch mode. Instead, we can use [swc](https://swc.rs/docs/usage/jest#usage) as a drop-in replacement to reduce the lag to one second.

chore: add speedy jest test compiler

---

lib/quoters/WebhookQuoter.ts

Found in cron logs
> circuit breaker triggered for 1ed189c4b20479e36acf74e2bc87e03bfdce765ecba6696970caee8299fc005f

chore: re-enable MM

---

bin/stacks/api-stack.ts

so that we get api-gateway level metrics broken down by resource, method, etc

chore: enable apiGW metric

---

bin/stacks/api-stack.ts

attempt to reduce lambda cold start time, see  https://github.com/aws/aws-cdk/issues/25492

chore: no external lambda dep

---

bin/stacks/api-stack.ts

Reverts Uniswap/uniswapx-parameterization-api#249

Revert "chore: no external lambda dep"

---

bin/config.ts
bin/stacks/cron-stack.ts
jest-dynamodb-config.js
lib/constants.ts
lib/cron/fade-rate.ts
lib/providers/circuit-breaker/s3.ts
lib/quoters/WebhookQuoter.ts
lib/repositories/base.ts
lib/repositories/fades-repository.ts
lib/repositories/switch-repository.ts
lib/repositories/timestamp-repository.ts
test/crons/fade-rate.test.ts
test/repositories/shared.ts
test/repositories/switch-repository.test.ts
test/repositories/timestamp-repository.test.ts

creates a `Timestamp` Dynamo table that tracks filler hash, lastCheckedPostTimestamp (last time the row is updated), and the timestamp that each filler should be blocked until.
The fade-rate cron job now calculates related timestamps based on recent order data from Redshift and `Timestamp` table

feat: Automated CB based on timestamps, Cron and DB part

---

package.json
yarn.lock

Unfortunately `cw-log-firehose-processor` is still on the old version

fix: add back aws-sdk v2

---

bin/app.ts

getting JVM OOM error in CodeBuild:
```
<--- JS stacktrace --->
--
59 |  
60 | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

fix: bump codebuild compute type

---

bin/stacks/kms-stack.ts

- Adds KMS stack to generate the co-signer key
- Once we know where we want to use this key we will pass the keyId into the lambda env
- Add the signer package dependency and then we can pass the KEY_ID to the KmsSigner class
- Then boom we have a secure signer in this service
- KMS Key ID passing - [link](https://github.com/Uniswap/fee-collector/blob/49c955983d6c737f21849214a9bc5557f473cfb6/bin/stacks/cron-stack.ts#L77)
- Using the KmsSigner from signer pkg - [link](https://github.com/Uniswap/fee-collector/pull/57/files#diff-4a07f99c79219b3a7f3f6018073077040f69a1d203cf376b80b802dd2f5c4258R43)

feat: add KMS stack

---

bin/app.ts
bin/stacks/api-stack.ts

Context: https://www.notion.so/uniswaplabs/AWS-Lambda-Best-Practices-781917c67edf4dcb96d22e38a6e46411
Adjust provisioned concurrencies for two lambdas that are not currently in use. ([slack thread](https://uniswapteam.slack.com/archives/C064HPY2B5H/p1707141838049609?thread_ts=1707141121.652199&cid=C064HPY2B5H)) 
For quote lambda, make the autoscaler more sensitive and allow it to move between 70-700. In otther words, reduce the minimum provisioned concurrency and allow for more fluctuation. The past 3 days the concurrencies never exceeded 150.
Link: https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/prod-us-east-2-GoudaParameterization-QuoteE2906A56-glqABjbF8MQv/aliases/live?tab=monitoring

Feat: Adjust concurrencies

---

lib/providers/analytics/firehose.ts
test/providers/analytics/firehose.test.ts

Previously @ConjunctiveNormalForm put out a PR (https://github.com/Uniswap/uniswapx-parameterization-api/pull/253) to update the firehose client used to log quoter endpoint metrics to use aws v3 sdk. In doing so, he added encoding logic on the data being logged that resulted in it not being in plain text new-line JSON in the destination S3 buckets. Removing the `base64` the encoding parameter produces the right format.

[fix] fix firehose logger output by removing base64 encoding

---

lib/entities/HardQuoteRequest.ts
lib/entities/index.ts
lib/handlers/hard-quote/handler.ts
lib/handlers/hard-quote/index.ts
lib/handlers/hard-quote/injector.ts
lib/handlers/hard-quote/schema.ts
lib/util/validator.ts
package.json
test/entities/HardQuoteRequest.test.ts
test/handlers/hard-quote/handler.test.ts
test/handlers/hard-quote/schema.test.ts
yarn.lock

- feat: add hard quote initial
- fix: tests

add hard quote

---

bin/stacks/analytics-stack.ts

Some of the firehose log processor lambdas have been failing with the following error:
```
"errorMessage": "ORDER_SERVICE_URL is not defined",
"stack": [
"Error: ORDER_SERVICE_URL is not defined",
"    at checkDefined (/lib/preconditions/preconditions.ts:3:11)",
"    at BA.buildContainerInjected (/lib/handlers/hard-quote/injector.ts:47:29)",
```
which is bizarre because
1) the hard-quote lambda does have `ORDER_SERVICE_URL` in its envVar (confirmed in aws console)
2) it should have nothing to do with the log processor lambdas
We attempt to fix them by passing in the envVars from the stack, which contains `ORDER_SERVICE_URL`, to all processor lambdas.

fix: pass in envVars to all lambdas

---

bin/stacks/analytics-stack.ts
bin/stacks/firehose-stack.ts

Reverts Uniswap/uniswapx-parameterization-api#276 to unblock pipeline
`Resource handler returned message: "CloudWatch Log Group Name is required if CloudWatch Logging is enabled (Service: Firehose, Status Code: 400, Request ID: fbb11366-b37a-c574-a5d3-950d418bbf26, Extended Request ID`
reverting for now as we don't need the logs at the moment

Revert "chore: enable firehose delivery error logs"

---

bin/stacks/api-stack.ts
lib/handlers/hard-quote/exports.ts
lib/handlers/hard-quote/index.ts
lib/handlers/index.ts

previously hard quote injector was built in the same index exports file
as the indicative quote injector, causing even indicative quote setup to
require a KMS_KEY_ID environment variable. This commit separates the
export into a separate file to decouple the env pulling.
Future improvement should do this same separation for rest of the
lambdas as well instead of having a global handlers/index

feat: separate hard quote exports

---

bin/stacks/api-stack.ts
lib/handlers/index.ts
lib/handlers/integration/rfq/exports.ts
lib/handlers/quote/exports.ts
lib/handlers/synth-switch/exports.ts

Decouples lambda handlers by moving the exports to individual files, and completes #283

fix: decouple handler exports

---

bin/stacks/analytics-stack.ts

Reverts Uniswap/uniswapx-parameterization-api#287
CDK doesn't support updating varchar type Redshift columns 😞

Revert "fix: change terminal_status type to varchar(18)"

---

bin/stacks/api-stack.ts
lib/entities/aws-metrics-logger.ts
lib/handlers/hard-quote/handler.ts
lib/handlers/hard-quote/injector.ts
lib/handlers/quote/injector.ts

set up a series of alarms for both soft-quote and hard-quote endpoints.
also, the existing `rfqSuccess/NonQuote...` alarms are broken because they have the wrong dimension, so fixed those as well

feat: separate soft and hard quote alarms; fix broken alarms

---

bin/stacks/api-stack.ts

So the `rfqOverallSuccessRate` doesn't really make sense because in most cases we get 0 quote back, and `NonQuoteRate` alarm should cover the extreme case when our fillers all become offline.

chore: remove nonsense metrics

---

bin/stacks/api-stack.ts

Pagerduty integration works by matching alarm names with `UniswapXParameterizationAPI-SEV2/SEV3` string

fix: alarm pagerduty integration

---

lib/entities/HardQuoteRequest.ts
lib/entities/QuoteRequest.ts
lib/entities/QuoteResponse.ts
lib/handlers/hard-quote/handler.ts
lib/handlers/quote/handler.ts
lib/handlers/quote/schema.ts
lib/quoters/WebhookQuoter.ts
lib/quoters/index.ts
lib/util/validator.ts
test/entities/HardQuoteRequest.test.ts
test/entities/QuoteRequest.test.ts
test/entities/QuoteResponse.test.ts
test/handlers/quote/handler.test.ts
test/handlers/quote/schema.test.ts
test/integ/quote.test.ts
test/providers/quoters/WebhookQuoter.test.ts

resolves #313 by adding a new field in the quote request that can specify the protocol version (`v1` or `v2`). Default to `v1` if none specified to be backward compatible with X v1.

feat: protocol field in request

---

bin/stacks/cron-stack.ts

This should turn on CB v2 for hard-quote endpoint

chore: add fade rate v2 cron

---

lib/config/chains.ts
lib/entities/HardQuoteResponse.ts
lib/handlers/hard-quote/handler.ts
lib/handlers/hard-quote/index.ts
lib/providers/analytics/firehose.ts
lib/util/chains.ts

Add QuoteResponse logs for Open Orders
https://linear.app/uniswap/issue/PROTO-256/add-open-order-quoteresponse-log

Add Open Order QuoteResponse log

---

lib/cron/fade-rate-v2.ts
lib/repositories/filler-address-repository.ts
test/repositories/filler-address-repository.test.ts

most fillers return checksumed addresses but a few return all-lowercase ones, so we need to reconcile on the server side.

fix(filler-addr-repo): always checksum addresses during reads/writes

---

lib/handlers/hard-quote/handler.ts

With 10 second delay in start time and +30 second end time, Open Orders are currently filling at the 20-30 seconds mark. We'd like to shorten this to start the Open Order in 1 sec for better UX.

Shorten Arbitrum v2 start time

---

lib/handlers/hard-quote/handler.ts

10-15 secs is too long on Arbitrum.. shorten the duration to see how that impacts fill time.

Decreasing auction duration to 10 sec

---

bin/config.ts

now that soft quoting depends on this table too, we need higher read capacity

fix: increase read capacity of timestamps table

---

lib/handlers/hard-quote/handler.ts
lib/handlers/hard-quote/injector.ts

I believe that when the lambda initializes, the KMSClient can end up in a bad state due to a temporary clock skew. The issue is not resolved until the next cold start causes a re-initialization.
See [incident doc](https://www.notion.so/uniswaplabs/GPA-Clock-Skew-31f2dc891d2e4bf2a672ec5634cd8f41?pvs=4) for more details.

Recreate KMSClient on each request

---

bin/stacks/api-stack.ts
bin/stacks/param-dashboard-stack.ts

- 5xx alarms
- use sum instead of avg
- set threshold to have caught prod issues
- quotePostErrorAlarmSev2
- uncomment alarm
There was no chart in our dashboard that indicated a failure; however the lambda specific charts *did* show the error. Because the lambdas are named dynamically (ex `prod-us-east-2-GoudaParameteriza-HardQuote29A66D69-y7GaCrCf5djc`), I'm unable to reference it statically. Instead, I iterate through all children of the app and create a dashboard for each lambda function like so:
```
scope.node.children
.filter((service) => service instanceof lambda.Function)
.map((service) => { 
...
```
Due to some AWS errors, I'm unable to test this in my personal AWS account.

Tighten alarms, new dashboards

---

bin/stacks/api-stack.ts

[I previously mistakenly adjusted the 4xx error alert instead of the 5xx one](https://github.com/Uniswap/uniswapx-parameterization-api/pull/356/files#diff-0ef77a1240d62d5b5e9e03d81d8698cd9d54ef6e1f268a1c31814400abec72e8R469). This reverts the 4xx alert and adjusts the `UniswapXParameterizationAPI-SEV2-5XX` instead.

Fix alert thresholds

---

lib/providers/circuit-breaker/s3.ts

I believe the clock skew problem is caused by a large time delta between when the client is created and when it's used. This change recreates the client on each request.

Fix S3 clock skew

---

bin/stacks/api-stack.ts

We have suspicions that there is netowrk congestion because of too many webhook calls; running a test we saw an improvement in latency so we'd like to keep it that way!

Increase memory on lambdas to improve latency

---

.eslintrc
lib/quoters/WebhookQuoter.ts

Takes too long (500ms+) to log the axios errors within `.catch` for some reason

fix: do not log axios timeout errors

---

lib/handlers/hard-quote/handler.ts

In statsig I'm doubling the slippage from 10 bps to 20 bps. To keep the same decay slope, I'm doubling the duration of the decay. The goal is to improve fill rate while keeping PI the same.

Increase order duration to 16s

---

bin/app.ts
bin/stacks/api-stack.ts

Beta environment is unable to deploy. This PR temporarily removes prod deployment from the pipeline (only Beta deployment) and removes the quote lambda.
`Stack:arn:aws:cloudformation:us-east-2:801328487475:stack/beta-us-east-2-GoudaParameterizationAPI/65c88a20-b2cb-11ed-94f4-024b19b40162 is in UPDATE_ROLLBACK_FAILED state and can not be updated.`

[TO-BE-REVERTED]: Temporarily remove lambda

---

bin/stacks/api-stack.ts
lib/handlers/hard-quote/injector.ts
lib/handlers/quote/injector.ts
lib/providers/circuit-breaker/dynamo.ts

- ClockSkew fix
- Remove usage of S3 client from the injector
- Alerting updates
- switched sev2 to use sum instead of avg and threshold of 100
- tighten sev3 to threshold of 20

Fix S3 clock skew and tighten 5xx alerts

---

lib/providers/compliance/index.ts
lib/providers/compliance/s3.ts
test/providers/compliance/s3.test.ts

Adds a new property `complianceListUrl` to the `FillerComplianceConfiguration`:
```
interface FillerComplianceConfiguration {
endpoints: string[];
addresses: string[];
complianceListUrl?: string;
}
```
Every 5 mins this endpoint is polled to get the latest version of the compliance list and added to the list in the static config.

Pull optional dynamic compliance list

---

bin/stacks/api-stack.ts

Lock down hard-quote to only Trading API. Generate a dev key for Frequent Swapper, UniswapX-tool, and E2E tests.

Add API keys for hard-quote endpoint

---

bin/stacks/analytics-stack.ts

The current 1 hr window is too small for some of these streams.

Update alert evaluation window to 12 hrs

---

bin/stacks/api-stack.ts

Makes the keys easier to identify in the portal

Give names to new API keys

---

lib/entities/HardQuoteRequest.ts

For EXACT_OUT orders, the input relative amounts are negative. This means that `getMinAmountOut()` will return the start amount if you pass in the input. Instead, to detect EXACT_IN, I check that either the input curve is undefined or all the values are 0.

bug(DutchV3): Fix bug in exact_out detection

---

bin/stacks/analytics-stack.ts
lib/handlers/blueprints/cw-log-firehose-processor.js
lib/handlers/blueprints/transformations.js
lib/handlers/index.ts

Reads Unimind logs from order service to create S3 buckets and set up Redshift
After merging this PR, we need to get the destination ARNs and then use them to create a subscription filter in order service. These filters watch the Lambda logs and send matching events to the S3 buckets

feat: create data tables from Unimind logs
