- bin/stacks/analytics-stack.ts
> chore: add tokenIn to postedOrders

- bin/stacks/api-stack.ts
- lib/repositories/switch-repository.ts
- test/repositories/switch-repository.test.ts
> fix: disable Sev2 4XX and keep Sev3

- .github/workflows/test.yml
- bin/stacks/api-stack.ts
- bin/stacks/cron-stack.ts
- jest-dynamodb-config.js
- lib/handlers/base/api-handler.ts
- lib/handlers/index.ts
- lib/handlers/synth-switch/handler.ts
- lib/handlers/synth-switch/index.ts
- lib/handlers/synth-switch/injector.ts
- lib/handlers/synth-switch/schema.ts
- lib/repositories/base.ts
- lib/repositories/switch-repository.ts
- test/repositories/switch-repository.test.ts
add `/synthetic-swtich/enabled` endpoint. 
will add some basic handler tests
> feat: add synth-switch lambda

- lib/cron/synth-switch.ts
- lib/repositories/switch-repository.ts
> fix: add debug logs

- lib/cron/synth-switch.ts
- lib/repositories/switch-repository.ts
> fix bug in finding orders matching configs

- lib/cron/synth-switch.ts
- lib/metrics/index.ts
add a few metrics to the synth-switch cron job, will build a dashboard on top as a followup
> feat: add metrics to synth-switch cron job

- bin/app.ts
https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
> fix: bump build image to support node 18

- bin/stacks/cron-stack.ts
- lib/cron/redshift-reaper.ts
- lib/providers/redshift/index.ts
- lib/repositories/analytics-repository.ts
- lib/repositories/base.ts
- lib/repositories/switch-repository.ts
- lib/util/time.ts
re-claim redshift cluster storage by deleting old entries.
> feat: redshift reaper cron

- lib/cron/fade-rate.ts
`fadeRateMap` is empty trying to figure out why
> chore: add some logs for debugging

- README.md
- lib/entities/QuoteRequest.ts
- lib/entities/QuoteResponse.ts
- lib/handlers/integration/rfq/handler.ts
- lib/handlers/quote/schema.ts
- lib/quoters/WebhookQuoter.ts
- test/handlers/quote/schema.test.ts
- test/providers/quoters/WebhookQuoter.test.ts
- send quoteId to MMs so they can connect their quotes to orders
> chore: send quoteId to mms

- bin/stacks/api-stack.ts
- cdk.context.json
- lib/providers/webhook/s3.ts
Adds static outbound IP for RFQ quote request.
https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/generate-a-static-outbound-ip-address-using-a-lambda-function-amazon-vpc-and-a-serverless-architecture.html
> Setup static outbound IPs

- bin/stacks/cron-stack.ts
- lib/cron/fade-rate.ts
> fix: circuit breaker trigger alarm

- bin/stacks/cron-stack.ts
to make pagerduty integration work
> fix: alarm name

- bin/stacks/cron-stack.ts
we were creating the same SNS topic in two different places
> fix: reuse chatbotTopic

- bin/stacks/cron-stack.ts
so we call `this.alarmsPerTable` for every dynamo table, which re-creates the same SNS topic and causes the deployment to fail:
```
const chatBotTopic = cdk.aws_sns.Topic.fromTopicArn(this, 'ChatbotTopic', chatbotSNSArn);
```
We never found this bug because we never passed in SNS chatbot param.
> fix: SNS topic creation

- lib/entities/QuoteRequest.ts
- lib/entities/QuoteResponse.ts
- lib/handlers/quote/handler.ts
- lib/handlers/quote/schema.ts
- test/entities/QuoteRequest.test.ts
- test/handlers/quote/handler.test.ts
- test/handlers/quote/schema.test.ts
- test/integ/quote.test.ts
- test/providers/quoters/WebhookQuoter.test.ts
Requires URA to send an additional field, numOutputs, and include that in RFQ requests to fillers
> feat: add numOutputs to rfq requests

- lib/repositories/fades-repository.ts
has to change to a new name due to incompatible schema
> fix: change fade rate view name

- lib/quoters/WebhookQuoter.ts
1. adds logging of axios error in the same way it is logged to CloudWatch
> [chore] add axios error to analytics events

- bin/app.ts
To reduce the number of cold starts hence the impact on latency in the short term.
> chore: increase prov conc to 150 for prod

- .github/workflows/semgrep.yml
Fixes the path issue in semgrep
> chore: fix semgrep path

- bin/app.ts
https://stackoverflow.com/questions/65277508/aws-code-pipeline-error-fatal-error-ineffective-mark-compacts-near-heap-limit-a
> fix: CodeBuild JVM OOM

- bin/stacks/api-stack.ts
- lib/handlers/index.ts
- lib/handlers/quote-v2/hard/injector.ts
- lib/handlers/quote-v2/indicative/injector.ts
- lib/handlers/quote-v2/injector.ts
add two api gateway endpoints:
- `POST /quote-v2/hard`
- `POST /quote-v2/indicative`
-
> feat: cdk for v2 quote endpoints

- bin/stacks/api-stack.ts
- lib/handlers/index.ts
This commit adds the hard quote endpoint into CDK
> feat: add hard quote CDK

- bin/stacks/analytics-stack.ts
- adds orderType field to ArchivedOrders table to indicate if an order is a limit order
> [chore] add to schema orderType field ArchivedOrders table

- bin/stacks/analytics-stack.ts
The actual change was made manually through aws console since CDK doesn't support it, this PR is created afterfact to catch up with the change
> fix: change terminal_status type to varchar(18)

- bin/stacks/analytics-stack.ts
Adding S3 and Redshift delivery alarms for the firehose streams we have.
> feat: firehsoe delivery alarms

- lib/handlers/hard-quote/handler.ts
- lib/handlers/quote/handler.ts
- lib/providers/webhook/index.ts
- lib/providers/webhook/mock.ts
- lib/providers/webhook/s3.ts
- lib/quoters/MockQuoter.ts
- lib/quoters/WebhookQuoter.ts
- lib/quoters/index.ts
- test/providers/quoters/WebhookQuoter.test.ts
> feat(WebhookConfig): add SupportedProtocol config

- lib/handlers/hard-quote/handler.ts
- lib/providers/order/index.ts
- lib/providers/order/mock.ts
- lib/providers/order/uniswapxService.ts
Per multiple fillers' request. Also needs https://github.com/Uniswap/uniswapx-service/pull/435
> chore: add requestId as part of POST body

- lib/handlers/hard-quote/handler.ts
- lib/handlers/hard-quote/schema.ts
- package.json
- test/integ/hard-quote.test.ts
- yarn.lock
We don't want to request RFQ when we know we want Open Orders
> Skip hard-quote on open orders

- lib/entities/QuoteResponse.ts
- lib/handlers/quote/handler.ts
- lib/quoters/MockQuoter.ts
- lib/quoters/WebhookQuoter.ts
- test/entities/QuoteResponse.test.ts
- test/handlers/hard-quote/handler.test.ts
- test/providers/quoters/WebhookQuoter.test.ts
completing [PROTO-248](https://linear.app/uniswap/issue/PROTO-248/dynamic-filler-mapping-in-dashboard)
> feat: add fillerName and endpoint to quote response logs

- lib/cron/fade-rate-v2.ts
- lib/repositories/fades-repository.ts
postTimestamp (alias of createdAt) seems to be a string
> fix: redshift column type parsing

- lib/constants.ts
- lib/cron/fade-rate-v2.ts
- lib/entities/aws-metrics-logger.ts
- lib/repositories/base.ts
- lib/repositories/timestamp-repository.ts
- test/crons/fade-rate-v2.test.ts
- test/providers/circuit-breaker/cb-provider.test.ts
- test/providers/quoters/WebhookQuoter.test.ts
- test/repositories/timestamp-repository.test.ts
track consecutive circuit breaker blocks of each filler and use that number to do exponential backoffs on the cooldown period.
> feat:(fade-rate-v2): adds exponential backoff

- lib/handlers/hard-quote/handler.ts
Start auction immediately and end after 7 secs.
> Shorten Arb auction

- lib/handlers/hard-quote/handler.ts
Goal is to increase fill rate while still having good fill time
> Extend Arbitrum auction by 1s

- .github/workflows/trufflehog.yml
Adds trufflehog secret scanning
> chore(infra): add trufflehog

- lib/quoters/WebhookQuoter.ts
- test/integ/hard-quote.test.ts
log and throw away because we don't care about the reponses
> fix: gracefully handle notifyBlock request

- lib/providers/webhook/s3.ts
Default to Dutchv2 for quoters if not specified
> V2 for all

- bin/stacks/analytics-stack.ts
- bin/stacks/api-stack.ts
- bin/stacks/param-dashboard-stack.ts
Attempt to fix the beta env by removing all lambdas. Will disable transition to prod.
> [TO-BE-REVERTED]: Remove all lambdas

- bin/stacks/analytics-stack.ts
Adding a Sev3 alarm for missing firehose data across all streams. Using a naming convention to trigger PagerDuty (thanks @ConjunctiveNormalForm)
This should have caught the log outage we experienced this past week:
> Add alarm for missing firehose data

- bin/stacks/api-stack.ts
- lib/constants.ts
- lib/handlers/hard-quote/handler.ts
- lib/handlers/hard-quote/injector.ts
- lib/handlers/quote/handler.ts
- lib/handlers/quote/injector.ts
- lib/quoters/WebhookQuoter.ts
- lib/quoters/index.ts
- lib/util/rfqValidator.ts
- test/entities/QuoteResponse.test.ts
> Add header, switch to StaticJsonRpcProvider

- lib/repositories/fades-repository.ts
We're getting the error: `ERROR: cannot change number of columns in view`
> Fix repo view

- package.json
- yarn.lock
Expanding permissioned token list
> chore: Update X SDK

- bin/app.ts
Fix KMS permission for integ tests
> Fix KMS perm

- bin/stacks/firehose-stack.ts
This reverts commit 503bccdfeb7a43e9160c2a0cef6c724c75ca8e92.
> Revert "feat: create write role for firehose stream (#426)"
